### ISSUE TITLE
Usage with Ground DB 2

### ISSUE THREAD

**Issue by promentol** [Urigo/meteor-rxjs#10]
Thank you for this package!
Are there any instruction, how to use meteor-rxjs with GroundDB 2?
This will be useful for cordova apps
Or are there any other mechanism we can cache in localstorage the result from observable and load from it when there is no internet access?

**Comment by barbatus** [comment]
This package is about wrapping Mongo cursor into RxJS observables, for the sake to use its API, particularly RxJS's operators, which can be helpful in many situations. But it's not about adding any caching or any other logic to the collections.

**Comment by promentol** [comment]
There is a package Ground DB which is adding caching logic in Mongo Collection
https://github.com/GroundMeteor/db
How can we can make this work with Meteor-rxjs? e.g. having RxJS Observables with zone operator alongside with Ground DB? 
Ground DB 2 is not extending Mongo Collection, so are there any Interface for MongoObservable to pass other type of collections beside MongoCollection with same API?
