### ISSUE TITLE
how to use it with SimpleSchema 

### ISSUE THREAD

**Issue by jalalat** [Urigo/meteor-rxjs#12]
I was using SimpleSchema (https://github.com/aldeed/meteor-simple-schema) earlier with my Mongo.Collections. Now changing the class to extend from MongoObservable.Collection is breaking the application. I do not know how i can attach SimpleSchema with my collection. Any advice will be welcome.

**Comment by ilacyero** [comment]
+1 Simple schema is amazing, I will need it to migrate to angular - meteor.

**Comment by barbatus** [comment]
Try it as
```ts
let col = new Mongo.Collection();
col.attachSchema(...);
let obs = new MongoObservable.Collection(col);
```

**Comment by ilacyero** [comment]
Hi @barbatus I tried but the insert or update uses the simple schema, but the bad thing, the collection  doesn't throw any error.

![image](https://cloud.githubusercontent.com/assets/1781538/19216610/23ea6bde-8d91-11e6-9422-03f6633b7672.png)

**Comment by ilacyero** [comment]
As you see in the image the error is correctly passed in the callback.

**Comment by barbatus** [comment]
so you'll need to use second argument of the subscribe
```ts
.subscribe(..., err => ...)
```

Or to use `catch` operator
```ts
obs.catch(err => ...).subscribe(...)
```

**Comment by jalalat** [comment]
it worked for me. Thanks a lot.

**Comment by ilacyero** [comment]
Yes barbatus I know, but the code is of **https://github.com/Urigo/meteor-rxjs/blob/master/src/ObservableCollection.ts#L71**. I am working in tutorial and the insert in client side doesn't throw exception, I will check with observable.

**Comment by leroadrunner** [comment]
Hi @barbatus, how do you manage to add the attachSchema property in an angular-meteor collection, since simple schema don't have this property and there's no typings for the collection2 package ? 
Thanks

**Comment by jalalat** [comment]
Hi @leroadrunner,

Check my code here:

```
class RepliesCollection extends Mongo.Collection < Reply > {
}
let RepliesMongo: any = new RepliesCollection(COLLECTIONS.REPLIES);
RepliesMongo.attachSchema(ReplySchema);
export const Replies = new MongoObservable.Collection < Reply >(RepliesMongo);
```

Let me know if you need any other info on this.

**Comment by leroadrunner** [comment]
Thanks @jalalat it absolutely works.
