### ISSUE TITLE
MeteorObservable.call does not seem to be working

### ISSUE THREAD

**Issue by IamCarbonMan** [Urigo/meteor-rxjs#152]
I have a method that returns an EJSON array (which is returned by a `Cursor.fetch()` call), which works like so:

    Meteor.call("search", {}, console.log)

but does not work like so:

    MeteorObservable.call("card_search", {}).subscribe(console.log)

In the first example, an Array is logged to the console, in the second, the console shows `undefined`.

**Comment by darkbasic** [comment]
Can you please share a sample repository showing the issue?

**Comment by IamCarbonMan** [comment]
Closing because I couldn't seem to reproduce the issue once I created a simple example.
