### ISSUE TITLE
MongoObservable.Collection's #find's #forEach not iterating on observable ?

### ISSUE THREAD

**Issue by ArThoX** [Urigo/meteor-rxjs#16]
Let a MyItems observable collection be mapped as so:

```
export let MyItems = new MongoObservable.Collection<MyItem>(
	new Mongo.Collection<MyItem>('myitem', { transform: (doc) => {
		return new MyItem(doc);
	}})
);
```

when I try to loop on the result of a `find`

`MyItems.find().forEach(v => { console.log(v._id); });`

I get the following error in the console:

`Property '_id' does not exist on type 'MyItems[]'.`

If I try to declare v as Myitem I would get

`'(v: MyItem) => void' is not assignable to parameter of type '(value: MyItem[]) => void'.`

**Any idea what could be wrong ? I am not expecting MyItem[] but MyItem.**

Typescript.d.ts was working before remapping my collections to MongoObservable's collections.

**Comment by ArThoX** [comment]
https://github.com/Urigo/meteor-rxjs/blob/68bc3b6bff2cd6c1bd62e288d1549b87e58e5cc2/dist/ObservableCollection.d.ts#L46

`find(...): ObservableCursor<T>;`

https://github.com/Urigo/meteor-rxjs/blob/master/src/ObservableCursor.ts#L7

`export class ObservableCursor<T> extends Observable<T[]> {`

So reading the .d.ts the `[]` is potentially expected.

In the other hand, at runtime `public_2.MyItems.find().forEach(i=>console.log(i))` does not prints T[] by each of my items.

I am confused.

**Comment by jafonseca** [comment]
I am having this issue as well. Were you able to find a resolution for this? After reviewing the `Observable ` definition below, it seams like the `forEach` function should only be expecting a single instance not an array. This looks like an error.

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/subscribe.md

**Comment by theobalkwill** [comment]
Similar issue here, accessing to the items property inside a forEach gives the following typescript error:
"Property 'propertyName' does not exist on type Item[]"

However I can still access the property. 

Any suggestion on how to get rid of that error?
Should I modify the .d.ts? Or should I access the item's property in a different way?
My code looks something similar to this:

```
items = Items.find();
items.forEach(item =>{
    console.log(item.propertyName); 
    //shows "Property 'propertyName' does not exist on type Item[]"
    //but still shows item's property when running the app
});
```

**Comment by slindeneau** [comment]
It appears to me to be incorrect as well. You can fix the error if you are sure that your dataset is going to be relatively small by calling .fetch() on the cursor.

````
items = Items.find().fetch();
items.forEach(item =>{
    console.log(item.propertyName); 
    //shows "Property 'propertyName' does not exist on type Item[]"
    //but still shows item's property when running the app
});
````
