### ISSUE TITLE
There is a way to do this?

### ISSUE THREAD

**Issue by pedrolucasoliva** [Urigo/meteor-rxjs#196]
Im trying to insert insert a new Entity (document) at mongo, but before I need call a meteor method to catch some sequence to it:
```
    public create(t: T): Observable<string> {
        return MeteorObservable.call("getSequence", this.service).map(seq => {
            t.seq = seq.padding;
            return this.collection.insert(t);
        });
    }
```
I have been in trouble with the return of Observable<string>.
Someone did it before?

ps:
this.collection = export const Entities = new MongoObservable.Collection<Entity>("entities");

**Comment by impcyber** [comment]
Try `this.collection.collection.insert`

**Comment by ardatan** [comment]
RxJS observables won't fire unless you subscribe them. So, this is not an issue related to `meteor-rxjs`.
You can try to do like below;
```ts
public create(t: T): Observable<string> {
        return MeteorObservable.call("getSequence", this.service).map(seq => {
        t.seq = seq.padding;
        return this.collection.insert(t);
}).subscribe(returnOfInsertion => {});
    }
```
Note that; the mutation on external variable inside `map`is not recommended because it will be side effect. You can learn more using RxJS Documentation.
