### ISSUE TITLE
Does this work with RxJS 6?

### ISSUE THREAD

**Issue by janKir** [Urigo/meteor-rxjs#211]
I'm thinking about to migrate my Angular-Meteor app to Angular 6 and hence RxJS 6, so I'm wondering if this library is compatible? Regarding to the [RxJS Update Guide](https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/preview), the `rxjs-compat` package in milestone 2 works for all libraries which depend on rxjs 5.5. Unfortunately, this library has a peer dependency of only rxjs 5.4. 

Is it still possible to migrate to RxJS 6 or when will this library support it?

Thanks!

**Comment by janKir** [comment]
I believe it would only need a pipable `zone()` method to be compatible. Should not be too hard to implement, I guess...

**Comment by ymchun** [comment]
@janKir yes, also need to fix rxjs import

**Comment by ardatan** [comment]
Incompability issues with RxJS and RxJS-Compat package is solved in the new release.
Feel free to open a new issue if you are still experiencing this problem.
Thank you!

**Comment by ymchun** [comment]
@ardatan your fix save my day! I've tried new release but still got this error
`Property 'zone' does not exist on type 'ObservableCursor<>'. Did you mean '_zone'?`

Thanks a lot

**Comment by ardatan** [comment]
@ymchun Your welcome!
Try this;
```ts
  import { zoneOperator } from 'meteor-rxjs';
  whateveritwas.pipe(zoneOperator())
```
