### ISSUE TITLE
How to use with Counts package

### ISSUE THREAD

**Issue by jalalat** [Urigo/meteor-rxjs#22]
I tried to use the Counts (https://github.com/percolatestudio/publish-counts) package in following way
```
Meteor.publish('commentCountPub', function(userId: string) {
    Counts.publish(this, 'commentCount', Comments.find(buildQuery.call(this, userId)).Cursor());
});
```
I got the error: TypeError: notifications_collection_1.Notifications.find(...).Cursor is not a function

How i can get cursor from the MongoObservable collection?

**Comment by dotansimha** [comment]
It should be:
```js
Meteor.publish('commentCountPub', function(userId: string) {
    Counts.publish(this, 'commentCount', Comments.find(buildQuery.call(this, userId)).cursor);
});
```

**Comment by jalalat** [comment]
It is working. Thanks.
