### ISSUE TITLE
ObservableCollections are not an instance of Observable

### ISSUE THREAD

**Issue by lgleim** [Urigo/meteor-rxjs#224]
```
import { Observable } from 'rxjs/Observable';
//import { ObservableCursor } from 'meteor-rxjs';

const x = SomeCollection.find({});
console.log(x instanceof Observable) // --> false
```

Kind of a mind bending issue given that ObservableCursor directly extends Observable (https://github.com/Urigo/meteor-rxjs/blob/master/src/ObservableCursor.ts#L7).

We first became aware of the issue by using Angular Material, which internally verifies the type of data sources as follows: https://github.com/angular/material2/blob/master/src/cdk/table/table.ts#L669

Any ideas?

**Comment by ardatan** [comment]
`meteor-rxjs` has been updated by using this DOCUMENTATION for RxJS 6. That's why, you have to import `Observable` from `rxjs` not `rxjs/Observable`.
