### ISSUE TITLE
"__extends is not defined" on Meteor v1.4.2.1

### ISSUE THREAD

**Issue by dgroch** [Urigo/meteor-rxjs#28]
I'm getting the error

`__extends is not defined`

when trying to import the MeteorObservable or MongoObservable classes on Meteor v1.4.2.1

I've searched the repo and can see the references to __extends in the class definitions, but can't see where the method is defined?

**Comment by dotansimha** [comment]
@dgroch, can you provide an example? tried to run with the tests application and it seems fine.

**Comment by dgroch** [comment]
@dotansimha I was actually running on `v1.4.2.2-beta.1`.  In the process of downgrading now and trying again. Seems the `__extends` are generated by Typescript? I don't need to be using typescript in my project, right?

**Comment by dgroch** [comment]
The error happens in `node_modules/meteor-rxjs/dist/bundles/index.umd.js` (see image below)

![meteor-rxjs-error](https://cloud.githubusercontent.com/assets/2666385/20287421/7ef38b8a-ab20-11e6-9f08-96ba6789c7a8.jpg)

**Comment by dotansimha** [comment]
@dgroch, please test with `meteor-rxjs@0.4.5`, just published it with a fix that should solve this issue and also add support for projects without typescript.

**Comment by dgroch** [comment]
Great, thanks @dotansimha I can confirm this squashes the errors re `__extends`.  I've bumped into another strange thing. When I wrap an existing Mongo Collection, the wrapper returns undefined.  But when I create a new collection by passing `null` to `ObservableCollection` it seems to work fine. 

Any clues?

**Comment by dotansimha** [comment]
@dgroch I am closing the issue if the issue was resolved.

Regarding your question - how do you wrap the existing Collection? can you share a code example?
