### ISSUE TITLE
Integration with 'collection-helpers'

### ISSUE THREAD

**Issue by pavlokitdev** [Urigo/meteor-rxjs#33]
Hello and thanks for nice lib!

Is any way to use 'collection-helpers' module
( https://atmospherejs.com/dburles/collection-helpers )
with meteor-rxjs?
Thanks!

**Comment by dotansimha** [comment]
Create all of you helpers, then use `MongoObservable.fromExisting` in order to wrap the **instance** of the collection.

Example:
```
let books = new Mongo.Collection('books');

books.helpers({
  author() {
    return Authors.findOne(this.authorId);
  }
});

export const Books = MongoObservable.fromExisting(books);
```

**Comment by pavlokitdev** [comment]
@dotansimha thanks!
