### ISSUE TITLE
ObservableCursor won't work with AsyncPipe

### ISSUE THREAD

**Issue by kamilkisiela** [Urigo/meteor-rxjs#4]
Won't work:

``` js
const Tasks = new MongoObservable.Collection<Task>('tasks');

@Component({
  selector: 'task-list',
  template: `<ul><li *ngFor="let task of tasks | async"></li></ul>`
})
class Tasks {
  tasks = Tasks.find();
}
```

It will but with `zone()`

``` js
const Tasks = new MongoObservable.Collection<Task>('tasks');

@Component({
  selector: 'task-list',
  template: `<ul><li *ngFor="let task of tasks | async"></li></ul>`
})
class Tasks {
  tasks = Tasks.find().zone(); // <--
}
```

**Comment by dotansimha** [comment]
It actually not needed to be bind to a zone, because that's what AsyncPipe should do... weird... 
I will debug it soon.
@kamilkisiela

**Comment by dotansimha** [comment]
@kamilkisiela I added a new examples directory with angular2 example - it works there great. Also tested with `ChangeDetectionStrategy.OnPush` and it works.

**Comment by barbatus** [comment]
@dotansimha how does ChangeDetectionStrategy.OnPush relate to this? AsyncPipe doesn't run zone it only marks itself for check (https://github.com/angular/angular/blob/14ee75924b6ae770115f7f260d720efa8bfb576a/modules/%40angular/common/src/pipes/async_pipe.ts#L146). Vile thing here is that it might seem working for simple examples (when everything happens synchronously), but will fail eventually for more complex once.
There was an idea to implement own version of AsyncPipe that runs zone.

**Comment by dotansimha** [comment]
Yeah you are right about OnPush. Do you have an example for a complex scenario? I tried some and it looks like it worked in all of them.

**Comment by barbatus** [comment]
@dotansimha I checked and turned out that Meteor.subscribe's callback is running now always in the zone. I think the issue might be in the promises. Before Meteor promise could possibly be initialized before zone-aware promise, so it was not patched. Zone.js actually patches everything including websockets. But that peace with promises was lost from patching.

**Comment by dotansimha** [comment]
@barbatus thanks, I see. 
Do you have any way to reproduce? I wan't to have a look on it

**Comment by barbatus** [comment]
@dotansimha I am saying I missed this point before. Now `.zone` probably not needed at all, except if observables are used out of Angular 2 zone. I'll check it out one more time and probably cleanup some stuff that not needed.
