### ISSUE TITLE
"Maximum call stack size exceeded" when passing objects via MeteorObservable.call()

### ISSUE THREAD

**Issue by sosnet** [Urigo/meteor-rxjs#40]
I get the error `Maximum call stack size exceeded` when I call `MeteorObservable.call('updateSpot', spot)`.

`spot` is an object of

```
  interface Spot {
    _id?: string;
    ownerId?: string;
    tourId?: string;
    title?: string;
    pictures?: string[];
    description?: string;
    actions?: any; //TODO: change

    lat?: number;
    lng?: number;
  }
```
```
main.js:68268 RangeError: Maximum call stack size exceeded
    at Function._.each._.forEach (main.js:101883)
    at Object.EJSON.clone (main.js:101887)
    at main.js:101887
    at Function._.each._.forEach (main.js:101883)
    at Object.EJSON.clone (main.js:101887)
    at main.js:101887
    at Function._.each._.forEach (main.js:101883)
    at Object.EJSON.clone (main.js:101887)
    at main.js:101887
    at Function._.each._.forEach (main.js:101883)
```

When I call `MeteorObservable.call('updateSpot', {_id: 123, test: 456})` I get no error..
I'm in an Ionic2 project.

**Comment by sosnet** [comment]
Ok, when I empty the actions array `spot.actions = []` before calling it's working. Is it my error?

**Comment by dotansimha** [comment]
Yeah it might be the error. please try to `JSON.stringify` you object in client side and see what happens. you might have a circular JSON object.

**Comment by sosnet** [comment]
Thx, that was the problem. Had a circular JSON object.
