### ISSUE TITLE
querying data by toggling on client

### ISSUE THREAD

**Issue by msio777** [Urigo/meteor-rxjs#78]
Hi,

I just wanna querying data (all checked (true and false) data are publish on client) by toggling checked variable but I get data just for the first time actually by initialization ( `getData()` is also placed in `ngOnInit()` wrapped by `MeteorObservable.subscribe` ) and never more by toggling. What Am I doing wrong ? 
Thanks for any help
Michal

```
checked:boolean = false
getData(){
Tasks.find({checked: this.checked})
  .map(tasks => tasks.length)
  .subscribe(todoCount => console.log(todoCount));
}

```

**Comment by msio777** [comment]
Actually it is working but If no tasks are found, subscribe is not fired. I'd expect that result is will be empty array. Why is it so ? 
Thanks

**Comment by jycouet** [comment]
Hi, 
I have the same issue. I don't know how to handle it.

**Comment by msio777** [comment]
My solution was that every time before getData() was called, I empty array and If Task.find will be called array will be filled else array is empty.

**Comment by jycouet** [comment]
Thx for your comment.
On my side, I would like to insert in the bd something when the result of the query is 0... So I can't go with your solution.

I found something else, did you try to wrap your code in: 
```
MeteorObservable.subscribe('MYSUBSCRIPTION', MYSUBSCRIPTIONARGS).subscribe(() => {
      MeteorObservable.autorun().subscribe(() => {

              //YOUR CODE

      });
 });
```

It look like it's working for me!

**Comment by msio777** [comment]
unfortunately it is not working for me :(

**Comment by jycouet** [comment]
@msio777 you set a publication from the server?
It worked for me after that!

**Comment by msio777** [comment]
solution is `startWith`
`Tasks.find({checked: this.checked}).startWith([]).map(tasks => tasks.length).subscribe(todoCount => console.log(todoCount));
}`
