### ISSUE TITLE
Zone.js 0.7.4 - View not updating

### ISSUE THREAD

**Issue by muehle28** [Urigo/meteor-rxjs#84]
The code inside the callback of a MongoObservable subscription is not updating the view. Its working when I put zone.run(). Before the update I used v0.6 without problems.

**Comment by activeperception** [comment]
I have the same problem (but doesn't seem related to zone.js version, things are still broken with 0.7.3 and 0.7.2) 

Furthermore a map operator is not invoked. E.g.

```javascript
const t = Task.find({}).map((tasks)=>{console.log(1); return tasks}).zone();

t.subscribe((tasks)=>{
 console.log('tasks: ', tasks);
})
```

the map operator is SKIPPED (no console.log) if I use zone()

I'm wondering why there aren't more people tripping into this issue.

**Comment by activeperception** [comment]
Found a workaround. Moved the .zone() to the MeteorObservable.subscribe. E.g.

```javascript
MeteorObservable.subscribe('AllTasks').zone().subscribe(() => {
     const t = Task.find({}).map((tasks)=>{console.log(1); return tasks}).zone();

     t.subscribe((tasks)=>{
       console.log('tasks: ', tasks);
    })
}
```
