### ISSUE TITLE
MongoObservable: IDE cannot import automatically

### ISSUE THREAD

**Issue by emilianosantucci** [Urigo/meteor-rxjs#9]
Hi guys,
I like this library but the IDE don't allow me to import `MongoObservable` automatically, like this:
`import {MongoObservable} from 'meteor-rxjs';`

In the same project, other class work fine.

Any suggestions?

**Comment by barbatus** [comment]
What does it mean it doesn't allow you import automatically? If you are saying that it's highlighted like there is no `MongoObservable` in `meteor-rxjs`, then make sure if it's installed. I just checked it works fine in the demo.

**Comment by emilianosantucci** [comment]
@barbatus i'm your nightmare in these days :D. 

The code completion of WebStorm can't show `MongoObservable` type when starting digitation as any other class but if I tape manually the import, all works fine.

I try with other classes of `meteor-rxjs` and code completion do its job.

Any idea?

**Comment by barbatus** [comment]
Well, I use Sublime and there is no feature like that (I doubt it's even possible). If other classes show up, that might be because of you mentioned them somewhere else, and they were saved for the autocomplete.

**Comment by barbatus** [comment]
Actually I was wrong. I just reloaded Sublime and it checked out one more time in the demo. So it works: when I start typing MongoObservale it shows `MongoOnservable _module_`.

**Comment by emilianosantucci** [comment]
@barbatus, code completion of IDEs like WebStorm or Eclipse, load from "libraries" (node_modules or typings in this case), not by "previous mention" like Sublime.
I will check if it is only my mystic configuration error.
What is the demo you mention here? Socially App?

**Comment by emilianosantucci** [comment]
Here some screenshot:

When try import automatically `MongoObservable`:
![screen shot 2016-10-06 at 16 56 54](https://cloud.githubusercontent.com/assets/13835650/19157682/65ad22f2-8be6-11e6-8efd-e43415021ba8.png)

After import manually `MongoObservable`:
![screen shot 2016-10-06 at 16 58 28](https://cloud.githubusercontent.com/assets/13835650/19157644/44eeec80-8be6-11e6-94f8-7b2170776499.png)

When, for example, try to import a class in the same package:
![screen shot 2016-10-06 at 17 02 49](https://cloud.githubusercontent.com/assets/13835650/19157812/d2f825a0-8be6-11e6-8891-0e24e82912d0.png)

I had clone socially project and it had the same behaviour.

Looking into source code I have seen that `MongoObservable` is an exported module differently `MeteorObservable` is declared as a class but I think it is irrelevant because I have imported other node dependencies as module too.

**Comment by barbatus** [comment]
Sublime has TypeScript plugin with the autocomplete as well. I was not sure that it works in the imports particularly (i.e., when typing  MongoObservable in `import {MongoObservable} from 'meteor-rxjs'`). As to your issue, have no idea why so far; it works fine in the todo demo for me (https://github.com/Urigo/angular-meteor/tree/master/packages/angular2-meteor/examples/todos-meteor-1.3)
